spring:
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/mma
    username: sa
    password:
    driverClassName: org.h2.Driver