spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: '/console'

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}


pl.zaprogramujzycie.mma:
  jwt:
    signKey: prodSignKey
    expiration: 86400000000