spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./spring-boot-h2-db.mv.db'
    username: 'sa'
    password:

pl.zaprogramujzycie.mma:
  jwt:
    signKey: prodSignKey
    expiration: 86_400_000_000