spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./spring-boot-h2-db.mv.db
    username: sa
    password:
    driverClassName: org.h2.Driver