CREATE TABLE families (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   CONSTRAINT pk_families PRIMARY KEY (id)
);

CREATE TABLE family_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   dtype VARCHAR(31),
   name VARCHAR(255) NOT NULL,
   is_child BOOLEAN NOT NULL,
   prescription_id BIGINT,
   family_id BIGINT NOT NULL,
   age INT NOT NULL,
   weight FLOAT NOT NULL,
   CONSTRAINT pk_family_members PRIMARY KEY (id)
);

CREATE TABLE medicines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   expiration_date TIMESTAMP with time zone NOT NULL,
   period_after_opening INT NOT NULL,
   CONSTRAINT pk_medicines PRIMARY KEY (id)
);

CREATE TABLE prescribed_medicines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   medicine_id BIGINT,
   dosage DOUBLE PRECISION,
   administration_times BLOB,
   CONSTRAINT pk_prescribed_medicines PRIMARY KEY (id)
);

CREATE TABLE prescriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   CONSTRAINT pk_prescriptions PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   login VARCHAR(255),
   password VARCHAR(255),
   family_id BIGINT,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE family_members ADD CONSTRAINT uc_family_members_name UNIQUE (name);

ALTER TABLE medicines ADD CONSTRAINT uc_medicines_name UNIQUE (name);

ALTER TABLE users ADD CONSTRAINT uc_users_login UNIQUE (login);

ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_FAMILY FOREIGN KEY (family_id) REFERENCES families (id);

ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIPTION FOREIGN KEY (prescription_id) REFERENCES prescriptions (id);

ALTER TABLE prescribed_medicines ADD CONSTRAINT FK_PRESCRIBED_MEDICINES_ON_MEDICINE FOREIGN KEY (medicine_id) REFERENCES medicines (id);

ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_FAMILY FOREIGN KEY (family_id) REFERENCES families (id);