 CREATE TABLE families (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_families PRIMARY KEY (id)
 );

 CREATE TABLE family_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250) NOT NULL,
    is_child NUMBER(1),
    family_id BIGINT NOT NULL,
    age INTEGER,
    weight DOUBLE PRECISION,
    CONSTRAINT pk_family_members PRIMARY KEY (id),
    CONSTRAINT fm_is_child CHECK (is_child IN (1,0))
 );

 CREATE TABLE medicines_to_families (
    families_id BIGINT NOT NULL,
    medicines_id BIGINT NOT NULL,
    primary key (families_id, medicines_id)
  );
