 CREATE TABLE medicines (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    expiration_date TIMESTAMP with time zone NOT NULL,
    period_after_opening INT NOT NULL,
    OWNER VARCHAR(256) NOT NULL,
    CONSTRAINT pk_medicines PRIMARY KEY (id)
 );

