 CREATE TABLE medicines (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    expiration_date TIMESTAMP with time zone NOT NULL,
    period_after_opening INT NOT NULL,
    owner BIGINT NOT NULL,
    CONSTRAINT pk_medicines PRIMARY KEY (id)
 );

 CREATE TABLE prescribed_medicines (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    medicine_id BIGINT,
    dosage DOUBLE PRECISION,
    first_dose TIME,
    dosage_interval INTEGER,
    owner VARCHAR(256) NOT NULL,
    CONSTRAINT pk_prescribed_medicines PRIMARY KEY (id)
 );

 ALTER TABLE prescribed_medicines ADD CONSTRAINT FK_PRESCRIBED_MEDICINES_ON_MEDICINE FOREIGN KEY (medicine_id) REFERENCES medicines (id);

