 CREATE TABLE medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    expiration_date TIMESTAMP with time zone NOT NULL,
    period_after_opening INT NOT NULL,
    family_id BIGINT NOT NULL,
    CONSTRAINT pk_medicines PRIMARY KEY (id)
 );

 ALTER TABLE medicines_to_families ADD CONSTRAINT FK_USERS_ON_FAMILIES FOREIGN KEY (medicines_id) REFERENCES medicines (id);
 ALTER TABLE medicines_to_families ADD CONSTRAINT FK_FAMILIES_ON_USERS FOREIGN KEY (families_id) REFERENCES families (id);

