 CREATE TABLE families (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_families PRIMARY KEY (id)
 );

 CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250) NOT NULL,
    is_child BOOlEAN,
    family_id BIGINT NOT NULL,
    prescription_id BIGINT NOT NULL,
    CONSTRAINT pk_family_members PRIMARY KEY (id)
 );

 CREATE TABLE family_members_child (
    age INTEGER,
    weight DOUBLE PRECISION,
    id BIGINT,
    FOREIGN KEY (id) REFERENCES members (id)
 );

 CREATE TABLE medicines_to_families (
    families_id BIGINT NOT NULL,
    medicines_id BIGINT NOT NULL,
    primary key (families_id, medicines_id)
  );

ALTER TABLE members ADD CONSTRAINT FK_PRESCRIPTION_ON_MEMBER FOREIGN KEY (prescription_id) REFERENCES  prescriptions (id);

ALTER TABLE medicines_to_families ADD CONSTRAINT FK_USERS_ON_FAMILIES FOREIGN KEY (medicines_id) REFERENCES medicines (id);
ALTER TABLE medicines_to_families ADD CONSTRAINT FK_FAMILIES_ON_USERS FOREIGN KEY (families_id) REFERENCES families (id);